const tg=window.Telegram?.WebApp; if(tg){tg.ready();tg.expand();}
let lang=localStorage.getItem('lang')||'ru';let cart=JSON.parse(localStorage.getItem('cart')||'{}');let fav=new Set(JSON.parse(localStorage.getItem('fav')||'[]'));let modalProduct=null;
const fmt=n=>new Intl.NumberFormat('ru-RU').format(n)+' сум';
const t={ru:{catalog:'Каталог',quiz:'Диагностика',favorites:'Избранное',cart:'Корзина',all:'Все категории',search:'Поиск по товарам',add:'В корзину',details:'Подробнее',checkout:'Оформить через Telegram',empty:'Корзина пуста'},uz:{catalog:'Katalog',quiz:'Diagnostika',favorites:'Sevimlilar',cart:'Savat',all:'Barcha kategoriyalar',search:'Mahsulot qidirish',add:'Savatga',details:'Batafsil',checkout:'Telegram orqali buyurtma',empty:'Savat bo‘sh'}};
function name(p){return lang==='ru'?p.nameRu:p.nameUz}function desc(p){return lang==='ru'?p.shortRu:p.shortUz}function use(p){return lang==='ru'?p.useRu:p.useUz}
function save(){localStorage.setItem('cart',JSON.stringify(cart));localStorage.setItem('fav',JSON.stringify([...fav]));renderCart();}
function productCard(p){return `<article class="product"><button class="heart" onclick="toggleFav('${p.id}')">${fav.has(p.id)?'♥':'♡'}</button><img src="${p.image}" alt="${name(p)}"><div class="product-body"><div class="brand">${p.brand}</div><h3>${name(p)}</h3><div class="desc">${desc(p)}</div><div class="price">${fmt(p.price)}</div><div class="actions"><button class="details" onclick="openProduct('${p.id}')">${t[lang].details}</button><button class="add" onclick="add('${p.id}')">＋</button></div></div></article>`}
function renderCatalog(){let q=document.querySelector('#search').value.toLowerCase();let c=document.querySelector('#category').value;let items=PRODUCTS.filter(p=>(c==='all'||p.category===c)&&(`${p.brand} ${name(p)} ${desc(p)}`.toLowerCase().includes(q)));document.querySelector('#grid').innerHTML=items.map(productCard).join('')}
function add(id){cart[id]=(cart[id]||0)+1;save();tg?.HapticFeedback?.impactOccurred('light')}
function change(id,d){cart[id]=(cart[id]||0)+d;if(cart[id]<=0)delete cart[id];save()}
function toggleFav(id){fav.has(id)?fav.delete(id):fav.add(id);save();renderCatalog();renderFav()}
function renderFav(){document.querySelector('#favGrid').innerHTML=PRODUCTS.filter(p=>fav.has(p.id)).map(productCard).join('')||'<p>Пока пусто.</p>'}
function renderCart(){let entries=Object.entries(cart);document.querySelector('#cartCount').textContent=entries.reduce((s,[,q])=>s+q,0);let subtotal=0;document.querySelector('#cartItems').innerHTML=entries.map(([id,q])=>{let p=PRODUCTS.find(x=>x.id===id);subtotal+=p.price*q;return `<div class="cart-row"><img src="${p.image}"><div><b>${name(p)}</b><div>${fmt(p.price)}</div><div class="qty"><button onclick="change('${id}',-1)">−</button><span>${q}</span><button onclick="change('${id}',1)">+</button></div></div><strong>${fmt(p.price*q)}</strong></div>`}).join('')||`<p>${t[lang].empty}</p>`;let delivery=subtotal===0||subtotal>=200000?0:30000;document.querySelector('#subtotal').textContent=fmt(subtotal);document.querySelector('#delivery').textContent=delivery?fmt(delivery):'Бесплатно';document.querySelector('#total').textContent=fmt(subtotal+delivery)}
function openProduct(id){modalProduct=PRODUCTS.find(p=>p.id===id);document.querySelector('#modalImage').src=modalProduct.image;document.querySelector('#modalBrand').textContent=modalProduct.brand;document.querySelector('#modalName').textContent=name(modalProduct);document.querySelector('#modalPrice').textContent=fmt(modalProduct.price);document.querySelector('#modalDesc').textContent=desc(modalProduct);document.querySelector('#modalVolume').textContent=modalProduct.volume;document.querySelector('#modalUse').textContent=use(modalProduct);document.querySelector('#modal').classList.add('open')}
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='favorites')renderFav();if(id==='cart')renderCart()}
function initQuiz(){let skins={dry:'Сухая',oily:'Жирная',combination:'Комбинированная',sensitive:'Чувствительная',normal:'Нормальная'};let concerns={acne:'Акне',postacne:'Постакне',pigmentation:'Пигментация',dehydration:'Сухость',redness:'Покраснение',pores:'Поры',dullness:'Тусклый тон'};document.querySelector('#skinOptions').innerHTML=Object.entries(skins).map(([k,v])=>`<button class="chip" data-value="${k}">${v}</button>`).join('');document.querySelector('#concernOptions').innerHTML=Object.entries(concerns).map(([k,v])=>`<button class="chip" data-value="${k}">${v}</button>`).join('');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>b.classList.toggle('selected'))}
function runQuiz(){let skin=document.querySelector('#skinOptions .selected')?.dataset.value;let concerns=[...document.querySelectorAll('#concernOptions .selected')].map(x=>x.dataset.value);let scored=PRODUCTS.map(p=>({p,score:(skin&&(p.skin.includes(skin)||p.skin.includes('all'))?3:0)+concerns.filter(c=>p.concerns.includes(c)).length*2+(p.category==='spf'?1:0)})).sort((a,b)=>b.score-a.score).slice(0,5).map(x=>x.p);document.querySelector('#quizResult').innerHTML=scored.map(productCard).join('')}
function checkout(){let items=Object.entries(cart).map(([id,qty])=>{let p=PRODUCTS.find(x=>x.id===id);return{id:p.id,name:p.nameUz,qty,price:p.price}});if(!items.length)return alert(t[lang].empty);let payload={type:'order',lang,items,subtotal:items.reduce((s,i)=>s+i.price*i.qty,0)};if(tg?.sendData){tg.sendData(JSON.stringify(payload));tg.close()}else{navigator.clipboard?.writeText(JSON.stringify(payload));alert('Откройте Mini App внутри Telegram для оформления заказа.')}}
function applyLang(){document.querySelector('#langBtn').textContent=lang.toUpperCase();document.querySelector('#search').placeholder=t[lang].search;document.querySelectorAll('.tabs button')[0].childNodes[0].nodeValue=t[lang].catalog+' ';document.querySelectorAll('.tabs button')[1].textContent=t[lang].quiz;document.querySelectorAll('.tabs button')[2].textContent=t[lang].favorites;document.querySelector('#checkout').textContent=t[lang].checkout;renderCatalog();renderFav();renderCart()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelector('#search').oninput=renderCatalog;document.querySelector('#category').onchange=renderCatalog;document.querySelector('#langBtn').onclick=()=>{lang=lang==='ru'?'uz':'ru';localStorage.setItem('lang',lang);applyLang()};document.querySelector('#closeModal').onclick=()=>document.querySelector('#modal').classList.remove('open');document.querySelector('#modalAdd').onclick=()=>{add(modalProduct.id);document.querySelector('#modal').classList.remove('open')};document.querySelector('#runQuiz').onclick=runQuiz;document.querySelector('#checkout').onclick=checkout;initQuiz();applyLang();
